In [1]:
import json 
import pandas as pd
import numpy as np

In [2]:
df_csv_visual = pd.read_csv("listings.csv")
df_csv_visual

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,27262,https://www.airbnb.com/rooms/27262,20241225065837,2024-12-25,city scrape,"AQA-No7, Great mattress, high speed internet",THE MATTRESS - KING KOIL - Camden Luxury 160x2...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,37177,...,4.97,4.75,4.71,00002433111,t,1,1,0,0,0.19
1,809874,https://www.airbnb.com/rooms/809874,20241225065837,2024-12-25,city scrape,Wonderfull Penthouse!!,NaN,NaN,https://a0.muscache.com/pictures/11813063/7d06...,4259738,...,4.92,4.86,4.91,00001240742,f,1,1,0,0,0.68
2,866381,https://www.airbnb.com/rooms/866381,20241225065837,2024-12-25,city scrape,Acropolis View Funky House,Welcome to a colorful 7th-floor penthouse in N...,NaN,https://a0.muscache.com/pictures/hosting/Hosti...,4551671,...,4.93,4.73,4.90,00002608390,f,1,1,0,0,0.28
3,886724,https://www.airbnb.com/rooms/886724,20241225065837,2024-12-25,city scrape,Luxury Boutique Appartment -Athens,NaN,The apartment is very conveniently located for...,https://a0.muscache.com/pictures/14659524/b33a...,4700824,...,4.89,4.28,4.72,00000052101,f,1,1,0,0,0.14
4,896212,https://www.airbnb.com/rooms/896212,20241225065837,2024-12-25,city scrape,Living like in a cottage in the center of Athens,An oasis of calm in the centre of a crowded ci...,Exarchia is considered the bohemian and altern...,https://a0.muscache.com/pictures/prohost-api/H...,4777984,...,4.93,4.82,4.93,00000206136,t,13,13,0,0,3.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14637,1318251942056598277,https://www.airbnb.com/rooms/1318251942056598277,20241225065837,2024-12-26,city scrape,Dreamy Athens Penthouse With Acropolis View,A unique penthouse in the historical center of...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,25811452,...,NaN,NaN,NaN,00003108542,t,3,3,0,0,NaN
14638,1318276742106864141,https://www.airbnb.com/rooms/1318276742106864141,20241225065837,2024-12-25,city scrape,Αθήνα κατάλυμα Rafaela,Stylish place to stay with many conveniences,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,666320836,...,NaN,NaN,NaN,00002888548,f,1,1,0,0,NaN
14639,1318307768558324736,https://www.airbnb.com/rooms/1318307768558324736,20241225065837,2024-12-25,city scrape,"Blueground | Ampelokipoi, AC, w/d, nr Lycabettus",Show up and start living from day one in Athen...,Ambelokipi is one of Athens’ largest districts...,https://a0.muscache.com/pictures/prohost-api/H...,221534605,...,NaN,NaN,NaN,00002764099,t,23,23,0,0,NaN
14640,1318405788507138933,https://www.airbnb.com/rooms/1318405788507138933,20241225065837,2024-12-25,city scrape,Cozy Nest,We welcome you to the fully renovated apartmen...,NaN,https://a0.muscache.com/pictures/miso/Hosting-...,650411545,...,NaN,NaN,NaN,00003072289,t,1,1,0,0,NaN
14641,1318601800941001079,https://www.airbnb.com/rooms/1318601800941001079,20241225065837,2024-12-25,city scrape,Vintage Elegance in Koukaki w/ balcony,"Welcome to a charming, vintage-inspired retrea...",Koukaki is a lively and historic neighborhood ...,https://a0.muscache.com/pictures/miso/Hosting-...,31290848,...,NaN,NaN,NaN,00003026761,t,70,70,0,0,NaN

In [31]:
df_csv_visual.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14642 entries, 0 to 14641
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            14642 non-null  int64
 1   listing_url                                   14642 non-null  object
 2   scrape_id                                     14642 non-null  int64
 3   last_scraped                                  14642 non-null  object
 4   source                                        14642 non-null  object
 5   name                                          14642 non-null  object
 6   description                                   14348 non-null  object
 7   neighborhood_overview                         7698 non-null   object
 8   picture_url                                   14642 non-null  object
 9   host_id                                       14642 non-null  int64
 10  host_url                                      14642 non-null  object
 11  host_name                                     14642 non-null  object
 12  host_since                                    14642 non-null  object
 13  host_location                                 10149 non-null  object
 14  host_about                                    7345 non-null   object
 15  host_response_time                            12903 non-null  object
 16  host_response_rate                            12903 non-null  object
 17  host_acceptance_rate                          13811 non-null  object
 18  host_is_superhost                             13868 non-null  object
 19  host_thumbnail_url                            14642 non-null  object
 20  host_picture_url                              14642 non-null  object
 21  host_neighbourhood                            5753 non-null   object
 22  host_listings_count                           14642 non-null  int64
 23  host_total_listings_count                     14642 non-null  int64
 24  host_verifications                            14642 non-null  object
 25  host_has_profile_pic                          14642 non-null  object
 26  host_identity_verified                        14642 non-null  object
 27  neighbourhood                                 7698 non-null   object
 28  neighbourhood_cleansed                        14642 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      14642 non-null  float64
 31  longitude                                     14642 non-null  float64
 32  property_type                                 14642 non-null  object
 33  room_type                                     14642 non-null  object
 34  accommodates                                  14642 non-null  int64
 35  bathrooms                                     13717 non-null  float64
 36  bathrooms_text                                14633 non-null  object
 37  bedrooms                                      14559 non-null  float64
 38  beds                                          13693 non-null  float64
 39  amenities                                     14642 non-null  object
 40  price                                         13722 non-null  object
 41  minimum_nights                                14642 non-null  int64
 42  maximum_nights                                14642 non-null  int64
 43  minimum_minimum_nights                        14642 non-null  int64
 44  maximum_minimum_nights                        14642 non-null  int64
 45  minimum_maximum_nights                        14642 non-null  int64
 46  maximum_maximum_nights                        14642 non-null  int64
 47  minimum_nights_avg_ntm                        14642 non-null  float64
 48  maximum_nights_avg_ntm                        14642 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              14568 non-null  object
 51  availability_30                               14642 non-null  int64
 52  availability_60                               14642 non-null  int64
 53  availability_90                               14642 non-null  int64
 54  availability_365                              14642 non-null  int64
 55  calendar_last_scraped                         14642 non-null  object
 56  number_of_reviews                             14642 non-null  int64
 57  number_of_reviews_ltm                         14642 non-null  int64
 58  number_of_reviews_l30d                        14642 non-null  int64
 59  first_review                                  12329 non-null  object
 60  last_review                                   12329 non-null  object
 61  review_scores_rating                          12329 non-null  float64
 62  review_scores_accuracy                        12329 non-null  float64
 63  review_scores_cleanliness                     12329 non-null  float64
 64  review_scores_checkin                         12329 non-null  float64
 65  review_scores_communication                   12329 non-null  float64
 66  review_scores_location                        12329 non-null  float64
 67  review_scores_value                           12329 non-null  float64
 68  license                                       14448 non-null  object
 69  instant_bookable                              14642 non-null  object
 70  calculated_host_listings_count                14642 non-null  int64
 71  calculated_host_listings_count_entire_homes   14642 non-null  int64
 72  calculated_host_listings_count_private_rooms  14642 non-null  int64
 73  calculated_host_listings_count_shared_rooms   14642 non-null  int64
 74  reviews_per_month                             12329 non-null  float64
dtypes: float64(17), int64(23), object(35)
memory usage: 8.4+ MB

In [32]:
pd.options.display.max_rows = 20

In [33]:
data = df_csv_visual.iloc [ : , [0,3,4,9,15,16,17,18,22,23,24,27,30,31,32,33,34,35,37,38,39,40,41,42,43,44,45,46,47,48,51,52,53,54,56,57,58,61,62,63,64,65,66,67,68,70,71,72,73,74]]
data

,id,last_scraped,source,host_id,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,host_total_listings_count,...,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,license,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,27262,2024-12-25,city scrape,37177,within an hour,100%,100%,t,4,12,...,4.86,4.97,4.75,4.71,00002433111,1,1,0,0,0.19
1,809874,2024-12-25,city scrape,4259738,within an hour,100%,96%,f,2,2,...,4.89,4.92,4.86,4.91,00001240742,1,1,0,0,0.68
2,866381,2024-12-25,city scrape,4551671,within a few hours,100%,97%,t,1,1,...,4.93,4.93,4.73,4.90,00002608390,1,1,0,0,0.28
3,886724,2024-12-25,city scrape,4700824,NaN,NaN,0%,f,1,1,...,4.88,4.89,4.28,4.72,00000052101,1,1,0,0,0.14
4,896212,2024-12-25,city scrape,4777984,within an hour,95%,100%,t,29,50,...,4.97,4.93,4.82,4.93,00000206136,13,13,0,0,3.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14637,1318251942056598277,2024-12-26,city scrape,25811452,within an hour,100%,100%,t,3,3,...,NaN,NaN,NaN,NaN,00003108542,3,3,0,0,NaN
14638,1318276742106864141,2024-12-25,city scrape,666320836,within a few hours,100%,NaN,f,2,2,...,NaN,NaN,NaN,NaN,00002888548,1,1,0,0,NaN
14639,1318307768558324736,2024-12-25,city scrape,221534605,within a few hours,86%,98%,f,53,1010,...,NaN,NaN,NaN,NaN,00002764099,23,23,0,0,NaN
14640,1318405788507138933,2024-12-25,city scrape,650411545,NaN,NaN,NaN,f,1,1,...,NaN,NaN,NaN,NaN,00003072289,1,1,0,0,NaN
14641,1318601800941001079,2024-12-25,city scrape,31290848,within an hour,100%,100%,NaN,109,119,...,NaN,NaN,NaN,NaN,00003026761,70,70,0,0,NaN

In [34]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14642 entries, 0 to 14641
Data columns (total 50 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            14642 non-null  int64
 1   last_scraped                                  14642 non-null  object
 2   source                                        14642 non-null  object
 3   host_id                                       14642 non-null  int64
 4   host_response_time                            12903 non-null  object
 5   host_response_rate                            12903 non-null  object
 6   host_acceptance_rate                          13811 non-null  object
 7   host_is_superhost                             13868 non-null  object
 8   host_listings_count                           14642 non-null  int64
 9   host_total_listings_count                     14642 non-null  int64
 10  host_verifications                            14642 non-null  object
 11  neighbourhood                                 7698 non-null   object
 12  latitude                                      14642 non-null  float64
 13  longitude                                     14642 non-null  float64
 14  property_type                                 14642 non-null  object
 15  room_type                                     14642 non-null  object
 16  accommodates                                  14642 non-null  int64
 17  bathrooms                                     13717 non-null  float64
 18  bedrooms                                      14559 non-null  float64
 19  beds                                          13693 non-null  float64
 20  amenities                                     14642 non-null  object
 21  price                                         13722 non-null  object
 22  minimum_nights                                14642 non-null  int64
 23  maximum_nights                                14642 non-null  int64
 24  minimum_minimum_nights                        14642 non-null  int64
 25  maximum_minimum_nights                        14642 non-null  int64
 26  minimum_maximum_nights                        14642 non-null  int64
 27  maximum_maximum_nights                        14642 non-null  int64
 28  minimum_nights_avg_ntm                        14642 non-null  float64
 29  maximum_nights_avg_ntm                        14642 non-null  float64
 30  availability_30                               14642 non-null  int64
 31  availability_60                               14642 non-null  int64
 32  availability_90                               14642 non-null  int64
 33  availability_365                              14642 non-null  int64
 34  number_of_reviews                             14642 non-null  int64
 35  number_of_reviews_ltm                         14642 non-null  int64
 36  number_of_reviews_l30d                        14642 non-null  int64
 37  review_scores_rating                          12329 non-null  float64
 38  review_scores_accuracy                        12329 non-null  float64
 39  review_scores_cleanliness                     12329 non-null  float64
 40  review_scores_checkin                         12329 non-null  float64
 41  review_scores_communication                   12329 non-null  float64
 42  review_scores_location                        12329 non-null  float64
 43  review_scores_value                           12329 non-null  float64
 44  license                                       14448 non-null  object
 45  calculated_host_listings_count                14642 non-null  int64
 46  calculated_host_listings_count_entire_homes   14642 non-null  int64
 47  calculated_host_listings_count_private_rooms  14642 non-null  int64
 48  calculated_host_listings_count_shared_rooms   14642 non-null  int64
 49  reviews_per_month                             12329 non-null  float64
dtypes: float64(15), int64(22), object(13)
memory usage: 5.6+ MB

In [35]:
#convertir  archivo filtrado a CVS
data.to_csv("Athenas_Grecia_Dt.csv")